server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://47.121.193.236:5432/heny-demo
    username: heny_demo
    password: heny_demo
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true